## Explore knowledge base

In [2]:
import lancedb

vector_db = lancedb.connect(uri = "knowledge_base")
vector_db.table_names()

['articles']

In [4]:
vector_db["articles"]

LanceTable(name='articles', version=9, _conn=LanceDBConnection(uri='c:\\Users\\eriku\\Desktop\\DataenginerSTI2024-2026\\Github\\AIgeneering_four_week_course\\10_pydanticai_rags\\knowledge_base'))

In [5]:
vector_db["articles"].to_pandas()

,doc_id,filepath,filename,content,embedding
0,dwarf_hotot,C:\Users\eriku\Desktop\DataenginerSTI2024-2026...,dwarf_hotot,Dwarf Hotot\nCountry\nof origin\nFrance\nUse S...,"[-0.0360854, 0.011616136, 0.015652055, -0.0470..."
1,dwarf_rabbit,C:\Users\eriku\Desktop\DataenginerSTI2024-2026...,dwarf_rabbit,A dwarf rabbit\n(Netherland Dwarf breed)\nBaby...,"[-0.015948843, -0.0020334467, 0.020679306, -0...."
2,holland_lop,C:\Users\eriku\Desktop\DataenginerSTI2024-2026...,holland_lop,Holland Lop\nHolland lop standing on her back ...,"[-0.026729755, 0.012941162, 0.009253166, -0.05..."
3,netherland_dwarf_rabbit,C:\Users\eriku\Desktop\DataenginerSTI2024-2026...,netherland_dwarf_rabbit,Netherland Dwarf rabbit\nCountry of\norigin\n ...,"[-0.010614065, 0.004320113, 0.013331566, -0.05..."

In [6]:
vector_db["articles"].search("a short rabbit").limit(3).to_list()

c:\Users\eriku\Desktop\DataenginerSTI2024-2026\Github\AIgeneering_four_week_course\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[{'doc_id': 'dwarf_rabbit',
  'filepath': 'C:\\Users\\eriku\\Desktop\\DataenginerSTI2024-2026\\Github\\AIgeneering_four_week_course\\10_pydanticai_rags\\data\\dwarf_rabbit.txt',
  'filename': 'dwarf_rabbit',
  'content': 'A dwarf rabbit\n(Netherland Dwarf breed)\nBaby Mini Satin rabbits\nBlue-eyed white - Satin coat\nDwarf rabbit\nDwarf rabbit refers either (formally) to a rabbit with the\ndwarfing gene,[1] or (informally) to any small breed of\ndomestic rabbit or specimen thereof, or (colloquially) to\nany small rabbit. Dwarfism is a genetic condition that\nmay occur in humans and in many animals, including\nrabbits. True dwarfism is often associated with a cluster\nof physical abnormalities,[2] including pituitary\ndwarfism. The process of dwarfing is used to selectively\nbreed for smaller stature with each generation. Small\nstature is a characteristic of neoteny, which may account\n(in part) for the attraction of dwarf animals.\nThe Netherland Dwarf is the smallest of the domestic rabbits.\nThe American Rabbit Breeders Association (ARBA)[3][4]\naccepts a weight range of 1.1–3.5 lb (0.50–1.59 kg), but 2.5 lb\n(1.1 kg) is the maximum allowed by the British Rabbit\nCouncil (BRC).[5] The small stature of the Netherland Dwarf\nwas initially the result of the dwarfing gene: dw. Its short\nneck and rounded face are additional features of neoteny.\nMany small rabbit breeds have the dwarfing gene, but the\nPolish and the Britannia Petite are among those that do not.\nThey have attained their small stature solely through selective\nbreeding of successively smaller generations (a process called\ndwarfing).\nSome small rabbits (often mixed breeds) are a false dwarf, a rabbit that did not inherit the dwarfing gene.\nOne of the smallest species of wild rabbit is the Marsh rabbit (Sylvilagus palustris), an excellent\nswimmer[6] that weighs 2.2–2.6 lb (1.00–1.18 kg).\nThe following table includes rabbit breeds currently recognized by ARBA[3][4] or by the BRC[5] that have\na maximum weight of 4 lb (1.8 kg). Also included is a small breed from Germany, the Teddy Dwarf.[7]\nSmall rabbits\nSmallest rabbit breeds\nPygmy rabbit\n(Sylvilagus idahoensis)\n375–500 grams (0.827–1.102 lb)\nDomestic rabbit breeds <4 lb (1.8 kg)\nBreed name Image Weight Ear\ntype\nNetherland\nDwarf\n1.1–2.5 lb\n(0.50–\n1.13 kg)\nerect\nBritannia\nPetite [US]\n1.5–2.5 lb\n(0.68–\n1.13 kg)\nerect\nTeddy Dwarf\n  Also called:\n    Teddyzwerg\n1.75–\n3.75 lb\n(0.79–\n1.70 kg)\nerect\nDwarf Hotot\n2–3 lb\n(0.91–\n1.36 kg)\nerect\nJersey Wooly\n2.5–3.5 lb\n(1.1–\n1.6 kg)\nerect\nPolish [US]\n2.5–3.5 lb\n(1.1–\n1.6 kg)\nerect\nLionhead\n 1.36–1.7 lb (0.62–\n0.77 kg) erect\nMiniature Lion Lop\n 1.5–1.6 lb (0.68–\n0.73 kg) lop\nMiniature Lop [UK/NL]\n 3.4–3.8 lb (1.5–1.7 kg) lop\nMiniature Cashmere Lop\n 3.5 lb (1.6 kg) lop\nAmerican Fuzzy Lop\n 3.5–4.0 lb (1.6–1.8 kg) lop\nPlush Lop (Miniature)\n 1.7–1.8 lb (0.77–\n0.82 kg) lop\nCuniculture\nHouse rabbit\nLethal dwarfism in rabbits\nLop rabbit\n1. Hu, Dou (May 2014). Identification and analysis of the dwarf mutation in domestic rabbits (ht\ntps://stud.epsilon.slu.se/6908/11/hu_d_140622.pdf) [Identifiering och karaktärisering av\ndvärg mutationen hos tamkaninen] (PDF) (Master\'s thesis). Examensarbete. Vol. 444.\nSee also\nReferences\nUppsala, Sweden: Department of Animal Breeding and Genetics, Swedish University of\nAgricultural Sciences. pp. 1–26. Retrieved 19 February 2018.\n2. Fiorello, Christine V.; German, R.Z. (February 1997). "Heterochrony within species:\ncraniofacial growth in giant, standard, and dwarf rabbits" (https://doi.org/10.1111%2Fj.1558-\n5646.1997.tb02406.x). Evolution. 51 (1): 250–261. doi:10.1111/j.1558-5646.1997.tb02406.x\n(https://doi.org/10.1111%2Fj.1558-5646.1997.tb02406.x). PMID 28568789 (https://pubmed.\nncbi.nlm.nih.gov/28568789). S2CID 205780205 (https://api.semanticscholar.org/CorpusID:2\n05780205).\n3. Standard of Perfection 2016–2020. American Rabbit Breeders Association. 2015.\nASIN B018GVBJK4 (https://www.amazon.com/dp/B018GVBJK4).\n4. "ARBA Recognized Breeds" (https://arba.net/). American Rabbit Breeders Association.\nRetrieved 19 February 2018.\n5. "Breed Standards 2016-2020" (https://web.archive.org/web/20180121125834/http://www.the\nbrc.org/Mono%20Breed%20Standards%20Book%20APRIL%202017%20small.pdf) (PDF).\nBritish Rabbit Council. Archived from the original (http://www.thebrc.org/Mono%20Breed%2\n0Standards%20Book%20APRIL%202017%20small.pdf) (PDF) on 21 January 2018.\nRetrieved 29 January 2018.\n6. Compton, Gail (29 September 2012). "Swimming Rabbit Surfaces" (http://www.staugustine.c\nom/living/garden/2012-09-28/swimming-rabbit-surfaces). Lifestyle. The St. Augustine\nRecord. St. Augustine, Florida. Retrieved 22 February 2018.\n7. "Herzlich Willkommen auf den Webseiten des Teddykaninchen-Clubs" (http://www.teddykani\nnchen-club.de/home_index.html). Teddykaninchen Club. Retrieved 22 February 2018.\nBreeds of Rabbits Chart (http://rabbitbreeders.us/rabbit-breeds) at rabbitbreeders.us\nSmall rabbit breeds (http://www.raising-rabbits.com/small-rabbit-breeds.html) at Raising-\nRabbits.com\nRetrieved from "https://en.wikipedia.org/w/index.php?title=Dwarf_rabbit&oldid=1308938546"\nExternal links\n\n',
  'embedding': [-0.015948843210935593,
   -0.0020334466826170683,
   0.020679306238889694,
   -0.054600466042757034,
   0.02577560395002365,
   -0.004715218674391508,
   0.006340425927191973,
   -0.004718989133834839,
   -0.021345384418964386,
   -0.029584553092718124,
   -0.0011485414579510689,
   -0.007551702205091715,
   0.022357765585184097,
   -0.01670808717608452,
   0.10667598247528076,
   0.008534681051969528,
   0.0026626931503415108,
   0.0023245096672326326,
   -0.01706472411751747,
   -0.01261846348643303,
   -0.017216157168149948,
   -0.0011074041249230504,
   0.011374457739293575,
   -0.018209539353847504,
   0.01095401681959629,
   0.00968591496348381,
   0.0003729744057636708,
   0.004318699240684509,
   0.03902449831366539,
   -0.014293551445007324,
   0.003881006734445691,
   -0.011479123495519161,
   0.00790280383080244,
   0.0060987938195466995,
   -0.00814730953425169,
   0.01082032173871994,
   0.03496255353093147,
   -0.0044966028071939945,
   -0.020221123471856117,
   0.016967982053756714,
   0.014455773867666721,
   0.026536021381616592,
   0.0021087394561618567,
   0.01342559140175581,
   -0.008127700537443161,
   0.018946871161460876,
   0.011038847267627716,
   -0.024420425295829773,
   -0.010972312651574612,
   0.02620633877813816,
   0.014260591007769108,
   0.000683506194036454,
   -0.006132746115326881,
   -0.187326118350029,
   -0.008311877958476543,
   0.008503332734107971,
   -0.00481425179168582,
   0.0014314025174826384,
   0.025218967348337173,
   -0.0066186608746647835,
   -0.017293555662035942,
   0.028934936970472336,
   -0.005691799800843,
   -0.01199263148009777,
   -0.009468277916312218,
   0.004396338947117329,
   -0.00011770971468649805,
   0.026946239173412323,
   0.001279613934457302,
   -0.014808391220867634,
   -0.0029487942811101675,
   0.0019332572119310498,
   -0.0025954488664865494,
   -0.012079057283699512,
   0.0008152254740707576,
   -0.03738752752542496,
   -0.005106878932565451,
   -0.013057854026556015,
   0.0030558465514332056,
   0.031342871487140656,
   0.0037424671463668346,
   -0.03813754767179489,
   -0.00047203723806887865,
   -0.005426087416708469,
   0.0024898278061300516,
   0.026301389560103416,
   -0.0009742844267748296,
   -0.010906429030001163,
   -0.00832113716751337,
   -0.005434798542410135,
   0.0031097405590116978,
   -0.0009512630640529096,
   0.0007324639009311795,
   0.006217740010470152,
   0.007117039989680052,
   0.008653489872813225,
   0.002302986104041338,
   -0.021154310554265976,
   -0.006394763942807913,
   0.010484466329216957,
   -0.008681409992277622,
   -0.02455168217420578,
   -0.0057976157404482365,
   0.008018563501536846,
   -0.01891544833779335,
   0.003768653143197298,
   -0.0029504243284463882,
   0.016141019761562347,
   0.01092823501676321,
   0.008205433376133442,
   0.01108870841562748,
   -0.015570126473903656,
   0.005980557296425104,
   0.014114188961684704,
   0.011769807897508144,
   -0.2039424180984497,
   -0.00880428310483694,
   -0.001977192936465144,
   -0.0020578301046043634,
   -0.0054606422781944275,
   0.004085404332727194,
   0.02874811738729477,
   0.0038423046935349703,
   -0.015770424157381058,
   -0.012043160386383533,
   0.008896642364561558,
   0.031747519969940186,
   0.010277423076331615,
   -0.015428160317242146,
   0.016778524965047836,
   -0.0304256621748209,
   -0.03238601237535477,
   -0.026283130049705505,
   0.013683316297829151,
   -0.0029977138619869947,
   0.036046821624040604,
   -0.006370763760060072,
   -0.014574808068573475,
   -0.011364971287548542,
   0.006121204700320959,
   -0.01496332697570324,
   -0.003211533185094595,
   0.021100202575325966,
   0.024585699662566185,
   -0.02028023824095726,
   -0.0027444891165941954,
   -0.008067113347351551,
   0.020659588277339935,
   -0.041671864688396454,
   -0.00905588734894991,
   -0.001753969700075686,
   -0.013224266469478607,
   -0.015964409336447716,
   -0.0028015112038701773,
   0.011685080826282501,
   -0.03550998866558075,
   -0.004405321087688208,
   -0.005980045069009066,
   -0.02863220125436783,
   0.0033901450224220753,
   0.006863077636808157,
   0.0015145961660891771,
   0.01133886817842722,
   -0.007287141866981983,
   -0.026593513786792755,
   0.015097794122993946,
   0.007953384891152382,
   0.023655308410525322,
   -0.003669502679258585,
   0.02532416209578514,
   0.00465392554178834,
   -0.00559628289192915,
   0.02329302579164505,
   0.006271026097238064,
   0.006022686138749123,
   0.011527272872626781,
   0.01299270335584879,
   0.010083599016070366,
   -0.005392013117671013,
   -0.0006189817213453352,
   0.0066805146634578705,
   -0.0002677273005247116,
   -0.005526788532733917,
   -0.021662570536136627,
   -0.004112675320357084,
   -0.014534835703670979,
   0.005320082884281874,
   -0.023847145959734917,
   -0.0017748483223840594,
   -0.011653870344161987,
   -0.01688615046441555,
   -0.008353105746209621,
   0.01967802830040455,
   -0.029460497200489044,
   0.00018586775695439428,
   0.024685202166438103,
   -0.0008636135025881231,
   0.00714769447222352,
   -0.01253773644566536,
   0.01488663349300623,
   -0.007633700966835022,
   0.008965318091213703,
   0.020040860399603844,
   0.019938822835683823,
   0.0009289560839533806,
   0.010904152877628803,
   -0.02519071102142334,
   -0.03212156891822815,
   0.02153889462351799,
   0.012938580475747585,
   -0.000633029907476157,
   -0.009133623912930489,
   0.008824135176837444,
   -0.005159391090273857,
   -0.019978655502200127,
   0.007745061069726944,
   -0.014324774034321308,
   -0.007367958780378103,
   -4.575423008645885e-05,
   -0.011555970646440983,
   -0.0017298288876190782,
   -0.000678293698001653,
   0.03266827389597893,
   0.0024538987781852484,
   -0.0012198816984891891,
   -0.014768282882869244,
   -0.012137982994318008,
   -0.019979052245616913,
   -0.011643416248261929,
   0.0121986772865057,
   -0.0034572964068502188,
   0.016202230006456375,
   0.0038417743053287268,
   -0.007369807455688715,
   0.013749069534242153,
   -0.016956351697444916,
   -0.0035876373294740915,
   0.02407466433942318,
   0.03851259499788284,
   -0.00860441755503416,
   -0.01725180633366108,
   -0.03313139081001282,
   -0.011011112481355667,
   0.008443044498562813,
   0.013440845534205437,
   0.01041016448289156,
   0.019488468766212463,
   -0.00994997937232256,
   0.013968242332339287,
   0.006939002312719822,
   -0.005741866305470467,
   0.007311468478292227,
   -0.008700387552380562,
   -0.00318695604801178,
   -0.01217431016266346,
   -0.01090372446924448,
   -0.006919628009200096,
   -0.006081696134060621,
   0.0031191923189908266,
   0.009917675517499447,
   -0.002166291931644082,
   0.004884263034909964,
   0.022076359018683434,
   -0.00368414050899446,
   0.005315826274454594,
   -0.0028624432161450386,
   -0.008006378076970577,
   0.008032910525798798,
   -0.009722309187054634,
   0.008377471007406712,
   0.016227515414357185,
   0.0018181013874709606,
   0.009550919756293297,
   -0.004492452368140221,
   0.002019920153543353,
   0.009990563616156578,
   -0.11316099762916565,
   0.01875501126050949,
   -0.006902171764522791,
   -0.019271526485681534,
   0.009689966216683388,
   -0.010171916335821152,
   -0.01450803317129612,
   -0.018734874203801155,
   0.0024343798868358135,
   0.012910050339996815,
   0.020529404282569885,
   0.007336565293371677,
   0.01699410378932953,
   -0.011473728343844414,
   0.017872385680675507,
   -0.01551668532192707,
   -0.027046876028180122,
   0.01361813023686409,
   0.008069906383752823,
   -0.029151003807783127,
   -0.005320252384990454,
   -0.006583772599697113,
   -0.01133901346474886,
   0.012055659666657448,
   -0.014425822533667088,
   -0.00434586126357317,
   -0.007543436251580715,
   0.023788586258888245,
   0.02235487662255764,
   -0.0005431941244751215,
   -0.005551674868911505,
   0.0227467343211174,
   0.00900974404066801,
   -0.019207052886486053,
   -0.008801299147307873,
   0.005171779543161392,
   -0.008421529084444046,
   -0.0016257492825388908,
   0.011372928507626057,
   0.0024075028486549854,
   0.02261788584291935,
   -0.021379699930548668,
   0.0008048584568314254,
   0.0267940703779459,
   -0.012117011472582817,
   0.012691390700638294,
   -0.01696324534714222,
   -0.006116749253123999,
   -0.024830034002661705,
   -0.0022533584851771593,
   -0.01251849066466093,
   -0.001034108572639525,
   0.008709092624485493,
   -0.029364071786403656,
   0.008255654014647007,
   -0.026520762592554092,
   0.017529049888253212,
   0.010726436041295528,
   0.018158910796046257,
   -0.00880306027829647,
   0.006821217946708202,
   -0.014109751209616661,
   -0.0035204545129090548,
   -0.0032397706527262926,
   0.020357206463813782,
   -0.009690727107226849,
   -0.01689579151570797,
   -0.021893789991736412,
   0.0032784477807581425,
   0.01428510993719101,
   0.009592623449862003,
   -0.018479451537132263,
   0.0038521045353263617,
   -0.031118080019950867,
   -0.01919950358569622,
   0.01778344251215458,
   -0.027553947642445564,
   -0.014174917712807655,
   0.005186682567000389,
   -0.009767194278538227,
   -0.0072595058009028435,
   0.006542155984789133,
   0.005136036314070225,
   0.01817668415606022,
   0.014300166629254818,
   0.01000343356281519,
   0.002904758555814624,
   -0.02708933688700199,
   -0.0012082954635843635,
   -0.01902093179523945,
   -0.003585763741284609,
   0.003999884240329266,
   -0.03139105066657066,
   -0.004376894328743219,
   -0.019245382398366928,
   0.003286947263404727,
   -0.017789162695407867,
   0.002536070067435503,
   0.014849143102765083,
   0.0040180860087275505,
   -0.020446060225367546,
   0.018664440140128136,
   0.014454291202127934,
   0.009000154212117195,
   0.005624367389827967,
   0.018554072827100754,
   -0.03103814087808132,
   -0.016987772658467293,
   -0.009387006051838398,
   0.018068470060825348,
   0.013924943283200264,
   0.022835450246930122,
   -0.015196832828223705,
   -0.016774961724877357,
   -0.00972807314246893,
   -0.014761700294911861,
   0.023268356919288635,
   0.02119900844991207,
   0.005746135488152504,
   0.023367464542388916,
   0.01017849799245596,
   -0.003519489197060466,
   0.006468783598393202,
   -0.02456539496779442,
   0.014233081601560116,
   0.010522517375648022,
   0.00463873241096735,
   0.002538279863074422,
   -0.02227598987519741,
   0.001989067066460848,
   -0.007953144609928131,
   -0.008142528124153614,
   -0.005405026953667402,
   -0.011352923698723316,
   0.01038633193820715,
   -0.0016533909365534782,
   -0.006326109170913696,
   -0.01067033875733614,
   -0.017329774796962738,
   0.023959627375006676,
   -0.013958505354821682,
   0.0016775622498244047,
   0.012235051952302456,
   -0.014363774098455906,
   -0.025301998481154442,
   0.010430178605020046,
   -0.00484627578407526,
   -0.010605541989207268,
   0.01662411354482174,
   -0.03520834445953369,
   0.002887715119868517,
   0.010044436901807785,
   -0.004657168406993151,
   0.021831408143043518,
   0.009901586920022964,
   -0.03406224027276039,
   -0.015564107336103916,
   -0.004763870500028133,
   -0.00029395619640126824,
   -0.02532113529741764,
   -0.0060648503713309765,
   -0.023140091449022293,
   -0.015051460824906826,
   -0.006556293461471796,
   0.03504951670765877,
   0.0013315555406734347,
   0.01471675280481577,
   -0.0027667563408613205,
   0.0073011526837944984,
   0.006399011239409447,
   -0.01394452154636383,
   0.013298031874001026,
   -0.019709888845682144,
   0.004454262554645538,
   0.011376975104212761,
   0.018826352432370186,
   0.01794867217540741,
   -0.0015708861174061894,
   -0.0006842018337920308,
   0.004535145591944456,
   0.004760400857776403,
   0.005029943771660328,
   -0.0353674553334713,
   0.01375542487949133,
   -0.01337435096502304,
   -0.015396809205412865,
   0.02108849585056305,
   0.018329810351133347,
   -0.00816408358514309,
   -0.007579911965876818,
   0.012290802784264088,
   0.013533414341509342,
   -0.003146815812215209,
   0.037114810198545456,
   0.00661647180095315,
   0.001474577933549881,
   0.01295948401093483,
   0.031708620488643646,
   -5.0949009164469317e-05,
   0.01407172903418541,
   0.017779823392629623,
   0.003931471612304449,
   0.0005660639726556838,
   -0.003350690472871065,
   0.005351857747882605,
   -0.013200395740568638,
   -0.014043884351849556,
   -0.006944059859961271,
   -0.0027845012955367565,
   0.028911491855978966,
   0.028302425518631935,
   0.004096090793609619,
   0.014593341387808323,
   0.011710467748343945,
   0.0009072715183719993,
   0.01972932182252407,
   0.018124423921108246,
   0.010924452915787697,
   -0.02358861267566681,
   -0.0020311553962528706,
   -0.01773170381784439,
   0.005637429188936949,
   0.027359576895833015,
   0.017378054559230804,
   -0.009311563335359097,
   -0.003305742982774973,
   -0.006148376502096653,
   -0.00038914874312467873,
   0.004427997395396233,
   0.010545948520302773,
   0.025539280846714973,
   -0.0011177400592714548,
   -0.024664256721735,
   -0.0002466337464284152,
   -0.006182610057294369,
   0.021925820037722588,
   -0.005022075958549976,
   -0.007459062151610851,
   0.020269880071282387,
   0.026350874453783035,
   -0.020350268110632896,
   0.0062850830145180225,
   -0.006137194577604532,
   -0.0007339123985730112,
   -0.00814228318631649,
   -0.01678691804409027,
   -0.010235567577183247,
   -0.002780131297186017,
   0.008751124143600464,
   0.00464664539322257,
   0.030376601964235306,
   0.004367041867226362,
   0.0029535333160310984,
   -0.013377493247389793,
   0.006136707961559296,
   0.02037399634718895,
   0.0026935390196740627,
   0.003881082870066166,
   -0.020716115832328796,
   0.004387775901705027,
   0.007899664342403412,
   -0.005297010764479637,
   0.0028224531561136246,
   0.010073577053844929,
   0.03192950412631035,
   0.0039672222919762135,
   0.01407182589173317,
   -0.029855258762836456,
   0.003566872328519821,
   -0.12940046191215515,
   -0.008657385595142841,
   0.0044852737337350845,
   -0.015103915706276894,
   -0.00725951511412859,
   0.0035855018068104982,
   -0.023701826110482216,
   -0.029141800478100777,
   0.011466572061181068,
   -0.018960831686854362,
   0.0071431477554142475,
   0.0033740417566150427,
   -0.0005743294022977352,
   0.02379569038748741,
   0.00595452357083559,
   0.002524653449654579,
   -0.013909298926591873,
   -0.0004820499452762306,
   0.012345807626843452,
   0.006531359627842903,
   0.00810251571238041,
   -0.007862966507673264,
   0.0055182864889502525,
   0.02641511894762516,
   -0.016183530911803246,
   -0.014833003282546997,
   -0.02251051738858223,
   -0.010056356899440289,
   0.008546858094632626,
   0.028586147353053093,
   6.375765951815993e-05,
   0.01157279871404171,
   -0.0124500822275877,
   -0.018823616206645966,
   -0.012286216020584106,

In [9]:
# Closest vector
vector_db["articles"].search("a short rabbit").limit(3).to_list()[0]["content"]

'A dwarf rabbit\n(Netherland Dwarf breed)\nBaby Mini Satin rabbits\nBlue-eyed white - Satin coat\nDwarf rabbit\nDwarf rabbit refers either (formally) to a rabbit with the\ndwarfing gene,[1] or (informally) to any small breed of\ndomestic rabbit or specimen thereof, or (colloquially) to\nany small rabbit. Dwarfism is a genetic condition that\nmay occur in humans and in many animals, including\nrabbits. True dwarfism is often associated with a cluster\nof physical abnormalities,[2] including pituitary\ndwarfism. The process of dwarfing is used to selectively\nbreed for smaller stature with each generation. Small\nstature is a characteristic of neoteny, which may account\n(in part) for the attraction of dwarf animals.\nThe Netherland Dwarf is the smallest of the domestic rabbits.\nThe American Rabbit Breeders Association (ARBA)[3][4]\naccepts a weight range of 1.1–3.5 lb (0.50–1.59 kg), but 2.5 lb\n(1.1 kg) is the maximum allowed by the British Rabbit\nCouncil (BRC).[5] The small stature of the Netherland Dwarf\nwas initially the result of the dwarfing gene: dw. Its short\nneck and rounded face are additional features of neoteny.\nMany small rabbit breeds have the dwarfing gene, but the\nPolish and the Britannia Petite are among those that do not.\nThey have attained their small stature solely through selective\nbreeding of successively smaller generations (a process called\ndwarfing).\nSome small rabbits (often mixed breeds) are a false dwarf, a rabbit that did not inherit the dwarfing gene.\nOne of the smallest species of wild rabbit is the Marsh rabbit (Sylvilagus palustris), an excellent\nswimmer[6] that weighs 2.2–2.6 lb (1.00–1.18 kg).\nThe following table includes rabbit breeds currently recognized by ARBA[3][4] or by the BRC[5] that have\na maximum weight of 4 lb (1.8 kg). Also included is a small breed from Germany, the Teddy Dwarf.[7]\nSmall rabbits\nSmallest rabbit breeds\nPygmy rabbit\n(Sylvilagus idahoensis)\n375–500 grams (0.827–1.102 lb)\nDomestic rabbit breeds <4 lb (1.8 kg)\nBreed name Image Weight Ear\ntype\nNetherland\nDwarf\n1.1–2.5 lb\n(0.50–\n1.13 kg)\nerect\nBritannia\nPetite [US]\n1.5–2.5 lb\n(0.68–\n1.13 kg)\nerect\nTeddy Dwarf\n  Also called:\n    Teddyzwerg\n1.75–\n3.75 lb\n(0.79–\n1.70 kg)\nerect\nDwarf Hotot\n2–3 lb\n(0.91–\n1.36 kg)\nerect\nJersey Wooly\n2.5–3.5 lb\n(1.1–\n1.6 kg)\nerect\nPolish [US]\n2.5–3.5 lb\n(1.1–\n1.6 kg)\nerect\nLionhead\n 1.36–1.7 lb (0.62–\n0.77 kg) erect\nMiniature Lion Lop\n 1.5–1.6 lb (0.68–\n0.73 kg) lop\nMiniature Lop [UK/NL]\n 3.4–3.8 lb (1.5–1.7 kg) lop\nMiniature Cashmere Lop\n 3.5 lb (1.6 kg) lop\nAmerican Fuzzy Lop\n 3.5–4.0 lb (1.6–1.8 kg) lop\nPlush Lop (Miniature)\n 1.7–1.8 lb (0.77–\n0.82 kg) lop\nCuniculture\nHouse rabbit\nLethal dwarfism in rabbits\nLop rabbit\n1. Hu, Dou (May 2014). Identification and analysis of the dwarf mutation in domestic rabbits (ht\ntps://stud.epsilon.slu.se/6908/11/hu_d_140622.pdf) [Identifiering och karaktärisering av\ndvärg mutationen hos tamkaninen] (PDF) (Master\'s thesis). Examensarbete. Vol. 444.\nSee also\nReferences\nUppsala, Sweden: Department of Animal Breeding and Genetics, Swedish University of\nAgricultural Sciences. pp. 1–26. Retrieved 19 February 2018.\n2. Fiorello, Christine V.; German, R.Z. (February 1997). "Heterochrony within species:\ncraniofacial growth in giant, standard, and dwarf rabbits" (https://doi.org/10.1111%2Fj.1558-\n5646.1997.tb02406.x). Evolution. 51 (1): 250–261. doi:10.1111/j.1558-5646.1997.tb02406.x\n(https://doi.org/10.1111%2Fj.1558-5646.1997.tb02406.x). PMID 28568789 (https://pubmed.\nncbi.nlm.nih.gov/28568789). S2CID 205780205 (https://api.semanticscholar.org/CorpusID:2\n05780205).\n3. Standard of Perfection 2016–2020. American Rabbit Breeders Association. 2015.\nASIN B018GVBJK4 (https://www.amazon.com/dp/B018GVBJK4).\n4. "ARBA Recognized Breeds" (https://arba.net/). American Rabbit Breeders Association.\nRetrieved 19 February 2018.\n5. "Breed Standards 2016-2020" (https://web.archive.org/web/20180121125834/http://www.the\nbrc.org/Mono%20Breed%20Standards%20Book%20APRIL%202017%20small.pdf) (PDF).\nBritish Rabbit Council. Archived from the original (http://www.thebrc.org/Mono%20Breed%2\n0Standards%20Book%20APRIL%202017%20small.pdf) (PDF) on 21 January 2018.\nRetrieved 29 January 2018.\n6. Compton, Gail (29 September 2012). "Swimming Rabbit Surfaces" (http://www.staugustine.c\nom/living/garden/2012-09-28/swimming-rabbit-surfaces). Lifestyle. The St. Augustine\nRecord. St. Augustine, Florida. Retrieved 22 February 2018.\n7. "Herzlich Willkommen auf den Webseiten des Teddykaninchen-Clubs" (http://www.teddykani\nnchen-club.de/home_index.html). Teddykaninchen Club. Retrieved 22 February 2018.\nBreeds of Rabbits Chart (http://rabbitbreeders.us/rabbit-breeds) at rabbitbreeders.us\nSmall rabbit breeds (http://www.raising-rabbits.com/small-rabbit-breeds.html) at Raising-\nRabbits.com\nRetrieved from "https://en.wikipedia.org/w/index.php?title=Dwarf_rabbit&oldid=1308938546"\nExternal links\n\n'

## Pdf to text

In [5]:
from pypdf import PdfReader

reader = PdfReader("data/Dwarf_Hotot.pdf")

reader

In [7]:
all_text = ""

for page in reader.pages:
    all_text += page.extract_text()
    
all_text

'Dwarf Hotot\nCountry\nof origin\nFrance\nUse Show, pets\nTraits\nFace\ncolor\nBlack, Blue or Chocolate eyebands\n(Lilac is also possible, however not\nrecognized by the American Rabbit\nBreeder\'s Association)\nColor White\nA Dwarf Hotot, 5 months old\nDwarf Hotot\nDwarf Hotot is a breed of domestic rabbit\ncharacterized by an entirely white coat, except for a\ncircle of another color around each eye.\nThe Dwarf Hotot is one of the more recent breeds to be\nrecognized by the ARBA, gaining acceptance in 1983.\nIt has never been without a strong following, but also\nhas never been among the most popular breeds.[1]\nThe much larger Blanc de Hotot was produced in the\nearly 1900s in an effort to produce a black-eyed white\nrabbit for meat and fur. In that era, large rabbits were\nvalued for their commercial value. But in later years,\nbig bunnies went out of style and people started\npursuing dwarf breeds.\nIn the 1970s, one breeder in East Germany and one in\nWest Germany started working on a Dwarf Hotot,\ncompletely independent of one another. One crossed a\nRuby-Eyed White Netherland Dwarf to a Blanc de\nHotot; the other didn\'t use a standard Hotot at all, but crossed a black\nNetherland Dwarf to a Dutch and bred out markings until only the\neyebands remained. The two strains were eventually united in 1979 to\nproduce the breed known today.[2]\nThe Dwarf Hotot was imported to the United States in 1980 by\nElizabeth Forstinger,[2] a rabbit breeder also known for her work in\nimporting and distributing the Holland Lop throughout the country.[3]\nForstinger bred the Dwarf Hotot further, eliminating blue and marbled\neye colors from the breed, and brought several Dwarf Hotots to show at\nARBA conventions each year until they were officially accepted as\nseparate from the Netherland Dwarf in 1984.[2]\nThe breed is of compact type and has a gentle rollback coat. Unlike the\nPolish, which as similar body type, the shoulders are supposed to be as\nwide as the hips, and not show any taper. The head set is not as high on the shoulders as that of a\nNetherland Dwarf, but should not rest on the table either. The head is bold and broad. Ears are carried in\nan upright V shape, and are disqualified if over 2 ¾ inches in length. The eyes are encircled with narrow\nHistorybands of colored fur. Ideal eyeband width equals the thickness of two pennies, and the bands of color are\neven all around the eye. Weak or streaky eyebands are faulted, but a complete break in the band is\ndisqualified.\nFor many years, the only accepted variety was white with black eyebands. In the year 2006, chocolate\nbanded Dwarf Hotots were accepted by the ARBA. Blue banded were accepted in 2020. The black, blue\nand chocolate banded bunnies are shown together.[4]\nThe Dwarf Hotot is strictly a fancy breed. At 3 pounds max, they are too small to be of commercial value.\nList of rabbit breeds\n1. Mann, Adam (2024-08-15). "Dwarf Hotot Rabbit: Breed Info, Pictures, Traits & Facts" (http\ns://pangovet.com/pet-breeds/rabbits/dwarf-hotot-rabbit-breed/). PangoVet. Retrieved\n2024-08-15.\n2. Whitman, Bob D. (October 2004). Domestic Rabbits & Their Histories: Breeds of the World.\nLeawood, KS: Leathers Publishing. pp. 148–149. ISBN 978-1-58597-275-3.\n3. "HLRSC History" (https://www.hlrsc.org/about-2-1). Holland Lop Rabbit Specialty Club.\nRetrieved 29 September 2024.\n4. "Current Certificates of Development". Domestic Rabbits. 47 (4). August 2019.\nDwarf Hotot Rabbit Breed History (http://rabbitbreeders.us/dwarf-hotot-rabbits)\nDifferent Breeds of Rabbits (http://rabbitbreeders.us/rabbit-breeds)\nhttps://www.adhrc.com/\nRetrieved from "https://en.wikipedia.org/w/index.php?title=Dwarf_Hotot&oldid=1285313662"\nSee also\nReferences\nExternal links\n'

In [8]:
len(all_text)

3692

## Check vector db

In [9]:
import lancedb

db = lancedb.connect("knowledge_base")

db["articles"].to_pandas()

,doc_id,filepath,filename,content,embedding
0,dwarf_hotot,C:\Users\eriku\Desktop\DataenginerSTI2024-2026...,dwarf_hotot,Dwarf Hotot\nCountry\nof origin\nFrance\nUse S...,"[-0.0360854, 0.011616136, 0.015652055, -0.0470..."
1,dwarf_rabbit,C:\Users\eriku\Desktop\DataenginerSTI2024-2026...,dwarf_rabbit,A dwarf rabbit\n(Netherland Dwarf breed)\nBaby...,"[-0.015948843, -0.0020334467, 0.020679306, -0...."
2,holland_lop,C:\Users\eriku\Desktop\DataenginerSTI2024-2026...,holland_lop,Holland Lop\nHolland lop standing on her back ...,"[-0.026729755, 0.012941162, 0.009253166, -0.05..."
3,netherland_dwarf_rabbit,C:\Users\eriku\Desktop\DataenginerSTI2024-2026...,netherland_dwarf_rabbit,Netherland Dwarf rabbit\nCountry of\norigin\n ...,"[-0.010614065, 0.004320113, 0.013331566, -0.05..."

In [11]:
db["articles"].search("dwarfing gene").limit(2).to_pandas()

,doc_id,filepath,filename,content,embedding,_distance
0,dwarf_rabbit,C:\Users\eriku\Desktop\DataenginerSTI2024-2026...,dwarf_rabbit,A dwarf rabbit\n(Netherland Dwarf breed)\nBaby...,"[-0.015948843, -0.0020334467, 0.020679306, -0....",0.611867
1,netherland_dwarf_rabbit,C:\Users\eriku\Desktop\DataenginerSTI2024-2026...,netherland_dwarf_rabbit,Netherland Dwarf rabbit\nCountry of\norigin\n ...,"[-0.010614065, 0.004320113, 0.013331566, -0.05...",0.642584

## Explore deployed function app

In [2]:
import requests
from dotenv import load_dotenv
import os

load_dotenv()

url = f"https://eriks-rabbit-llm.azurewebsites.net/rag/query?code={os.getenv('FUNCTION_APP_API')}" 

response = requests.post(url, json={"prompt": "rabbit diet"})
response